name = "StatisticalTheories"
uuid = "a324afab-c284-4fe4-8b6d-fd3ed5a0fbfc"
license = "MIT"
authors = ["AlgebraicJulia Developer <email@algebraicjulia.org>"]
version = "0.0.1"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"

[compat]
Catlab = "^0.14"
julia = "1.9"
